apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: profileservice 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: profileservice 
    spec:
      containers:
        - name: profileservice 
          image: acubedcr.azurecr.io/profileservice
          ports:
          - containerPort: 80