apiVersion: v1
kind: Service
metadata:
    name: profile-service
    namespace: acubed
    labels:
      app: profile-service
spec:
    clusterIP: None
    ports:
    - port: 50551 
      name: profile-service
    selector:
      app: profile-service