apiVersion : apps/v1
kind: Deployment
metadata:
    name: profile-service 
    namespace: acubed
    labels:
      app: profile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service 
    spec:
      containers:
        - name: profile-service 
          imagePullPolicy: Never
          image: profile-service
          ports:
          - containerPort: 50551
